### ISSUE TITLE
更新adb

### ISSUE THREAD

**Issue by zzjoey** [EDISON-Z/Brevent-bat#1]
能不能更新一下release的adb版本
已经打包好了PowerShell版本的 [Brevent-P](https://dwz.cn/3cqeKD0m)
支持Android9.0 Pie

这个脚本很好用，感谢

**Comment by EdisonJwa** [comment]
抱歉,因为 GitHub 没有给我发送通知,导致我现在才看到您的 issue,我刚刚已经将 adb 更新为最新版本
> adb 来源: [Android 调试桥 (adb)](https://developer.android.com/studio/command-line/adb#top_of_page)
